// June 20, 2022 Bot API 6.1
module.exports = [
  // 'kickChatMember', похоже этого метода больше 'нет','

  'getMe',
  'logOut',
  'close',
  'sendMessage',
  'Formatting options',
  'forwardMessage',
  'copyMessage',
  'sendPhoto',
  'sendAudio',
  'sendDocument',
  'sendVideo',
  'sendAnimation',
  'sendVoice',
  'sendVideoNote',
  'sendMediaGroup',
  'sendLocation',
  'editMessageLiveLocation',
  'stopMessageLiveLocation',
  'sendVenue',
  'sendContact',
  'sendPoll',
  'sendDice',
  'sendChatAction',
  'getUserProfilePhotos',
  'getFile',
  'banChatMember',
  'unbanChatMember',
  'restrictChatMember',
  'promoteChatMember',
  'setChatAdministratorCustomTitle',
  'banChatSenderChat',
  'unbanChatSenderChat',
  'setChatPermissions',
  'exportChatInviteLink',
  'createChatInviteLink',
  'editChatInviteLink',
  'revokeChatInviteLink',
  'approveChatJoinRequest',
  'declineChatJoinRequest',
  'setChatPhoto',
  'deleteChatPhoto',
  'setChatTitle',
  'setChatDescription',
  'pinChatMessage',
  'unpinChatMessage',
  'unpinAllChatMessages',
  'leaveChat',
  'getChat',
  'getChatAdministrators',
  'getChatMemberCount',
  'getChatMember',
  'setChatStickerSet',
  'deleteChatStickerSet',
  'answerCallbackQuery',
  'setMyCommands',
  'deleteMyCommands',
  'getMyCommands',
  'setChatMenuButton',
  'getChatMenuButton',
  'setMyDefaultAdministratorRights',
  'getMyDefaultAdministratorRights',

  'InlineQuery',
  'answerInlineQuery',
  'InlineQueryResult',
  'InlineQueryResultArticle',
  'InlineQueryResultPhoto',
  'InlineQueryResultGif',
  'InlineQueryResultMpeg4Gif',
  'InlineQueryResultVideo',
  'InlineQueryResultAudio',
  'InlineQueryResultVoice',
  'InlineQueryResultDocument',
  'InlineQueryResultLocation',
  'InlineQueryResultVenue',
  'InlineQueryResultContact',
  'InlineQueryResultGame',
  'InlineQueryResultCachedPhoto',
  'InlineQueryResultCachedGif',
  'InlineQueryResultCachedMpeg4Gif',
  'InlineQueryResultCachedSticker',
  'InlineQueryResultCachedDocument',
  'InlineQueryResultCachedVideo',
  'InlineQueryResultCachedVoice',
  'InlineQueryResultCachedAudio',
  'InputMessageContent',
  'InputTextMessageContent',
  'InputLocationMessageContent',
  'InputVenueMessageContent',
  'InputContactMessageContent',
  'InputInvoiceMessageContent',
  'ChosenInlineResult',
  'answerWebAppQuery',
  'SentWebAppMessage',

  'editMessageText',
  'editMessageCaption',
  'editMessageMedia',
  'editMessageReplyMarkup',
  'stopPoll',
  'deleteMessage',

  'sendInvoice',
  'createInvoiceLink',
  'answerShippingQuery',
  'answerPreCheckoutQuery',

  'sendGame',

  'Update',
  'getUpdates',
  'setWebhook',
  'deleteWebhook',
  'getWebhookInfo',

  'sendSticker',
  'getStickerSet',
  'uploadStickerFile',
  'createNewStickerSet',
  'addStickerToSet',
  'setStickerPositionInSet',
  'deleteStickerFromSet',
  'setStickerSetThumb',

  'setPassportDataErrors',

  'setGameScore',
  'getGameHighScores',
];