// June 20, 2022 Bot API 6.1
module.exports = [
  // 'kickChatMember', похоже этого метода больше нет

  'getMe',
  'logOut',
  'close',
  'sendMessage',
  'forwardMessage',
  'copyMessage',
  'sendPhoto',
  'sendAudio',
  'sendDocument',
  'sendVideo',
  'sendAnimation',
  'sendVoice',
  'sendVideoNote',
  'sendMediaGroup',
  'sendLocation',
  'editMessageLiveLocation',
  'stopMessageLiveLocation',
  'sendVenue',
  'sendContact',
  'sendPoll',
  'sendDice',
  'sendChatAction',
  'getUserProfilePhotos',
  'getFile',
  'banChatMember',
  'unbanChatMember',
  'restrictChatMember',
  'promoteChatMember',
  'setChatAdministratorCustomTitle',
  'banChatSenderChat',
  'unbanChatSenderChat',
  'setChatPermissions',
  'exportChatInviteLink',
  'createChatInviteLink',
  'editChatInviteLink',
  'revokeChatInviteLink',
  'approveChatJoinRequest',
  'declineChatJoinRequest',
  'setChatPhoto',
  'deleteChatPhoto',
  'setChatTitle',
  'setChatDescription',
  'pinChatMessage',
  'unpinChatMessage',
  'unpinAllChatMessages',
  'leaveChat',
  'getChat',
  'getChatAdministrators',
  'getChatMemberCount',
  'getChatMember',
  'setChatStickerSet',
  'deleteChatStickerSet',
  'answerCallbackQuery',
  'setMyCommands',
  'deleteMyCommands',
  'getMyCommands',
  'setChatMenuButton',
  'getChatMenuButton',
  'setMyDefaultAdministratorRights',
  'getMyDefaultAdministratorRights',

  'answerInlineQuery',
  'answerWebAppQuery',

  'editMessageText',
  'editMessageCaption',
  'editMessageMedia',
  'editMessageReplyMarkup',
  'stopPoll',
  'deleteMessage',

  'sendInvoice',
  'createInvoiceLink',
  'answerShippingQuery',
  'answerPreCheckoutQuery',

  'sendGame',

  'getUpdates',
  'setWebhook',
  'deleteWebhook',
  'getWebhookInfo',

  'sendSticker',
  'getStickerSet',
  'uploadStickerFile',
  'createNewStickerSet',
  'addStickerToSet',
  'setStickerPositionInSet',
  'deleteStickerFromSet',
  'setStickerSetThumb',

  'setPassportDataErrors',

  'setGameScore',
  'getGameHighScores'
];
